# Generated by Django 6.1 on 2026-09-06 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='opened_challenge_log',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
